name: MCOreGenerator
description: Customize the cobblestone generator!
version: 0.1
api-version: 1.15
main: nl.codestix.oregenerator.MCOreGeneratorPlugin
author: Stijn Rogiest
commands:
  cobble:
    usage: /cobble [select <type1> <type2> | deselect | remove | set <type> <chance> | unset <type>]
    description: List chances or set chance.

